name              "workers"
maintainer        "Juan Manuel Torres"
maintainer_email  "kinojman@gmail.com"
license           "Apache License v2"
description       "Uses supervisor to start and manage processes"
version           "1.0.0"
